# Generated by Django 4.2.23 on 2025-12-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_semester_is_active_delete_events_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketselection',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_selections', to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketselection',
            unique_together={('user', 'event')},
        ),
    ]
